-- AlterTable
ALTER TABLE "hotels" ADD COLUMN     "maxAdults" INTEGER NOT NULL DEFAULT 16,
ADD COLUMN     "maxChildren" INTEGER NOT NULL DEFAULT 5,
ADD COLUMN     "maxInfants" INTEGER NOT NULL DEFAULT 5,
ADD COLUMN     "maxPets" INTEGER NOT NULL DEFAULT 2;
